version: 2.1

jobs:
  docker-image:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name : Build & Run Docker Image
          command : |
            docker build -t node-js-sample .
            docker run -d -p 8080:8080 node-js-sample
            sleep 3
            docker exec curl http://localhost:8080
            
workflows:
  say-hello-workflow:
    jobs:
      - docker-image

