version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name : Build Docker Image
          command : |
            docker build -t node-js-sample .
                    
  run-docker-image:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name : Run Docker Image
          command : |
            docker run -d -p 8080:8080 node-js-sample
            sleep 3
            curl http://localhost:8080
            
workflows:
  say-hello-workflow:
    jobs:
      - build-docker-image
      - run-docker-image

