version: 2.1
jobs:
  build-and-test:
    docker:
        - image: cimg/base:stable
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build docker image
            command: |
                docker build -t node-js-sample .
        - run:
            name: Run and Test docker image
            command: |
                docker run -d -p 8080:8080 --name node-js-sample node-js-sample
                sleep 3
                docker exec node-js-sample curl --retry 10 --retry-connrefused http://localhost:8080
workflows:
    version: 2
    build-and-test:
        jobs:
        - build-and-test